[package]
name = "eh-alpha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared-bus = { path = "../../", features = ["eh-alpha"] }